# Generated by Django 2.2.4 on 2019-10-11 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_investment_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='cust_number',
            new_name='customer_number',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='zipcode',
            new_name='zip_code',
        ),
    ]
